; CONSIDER THERE ARE DATA1 & DATA2 IN ADD. 1H & 3H (16-BIT) DATA  
MOV [1H],3421H
MOV [3H],5620H
; ABOVE IS AN ASSUMPTION!
MOV AX , 1H
MOV BX , 3H
; ADDRESSES IN AX AND BX
MOV DI , AX
MOV SI , [DI] ; FIRST WORD IN SI
XCHG SI , [BX]  ; FIRST WORD IN THE SECOND ADD. AND SND WORD IN SI
XCHG SI , [DI]  ; SND WORD IN FIRST ADD. AND FIRST WORD IN SI
