; CONSIDER THERE ARE DATA1 & DATA2 IN ADD. 1H & 3H (16-BIT) DATA  
MOV [1H],3421H
MOV [3H],5620H
; ABOVE IS AN ASSUMPTION!
MOV AX , 1H
MOV BX , 3H
MOV DI , AX
MOV AX , [DI]   ; AX IS NOT INDIRECTLY ADDRESSABLE! + IT'S A WORD SO WORD PTR IS NOT NEEDED FOR DI!
MOV CX , [BX]
MOV [DI] , CX
MOV [BX] , AX
; END OF THE CODE
